services:
  backend:
    image: sqbackend
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=94826a23ffc34aa1b645ecf2a57e732f
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: 94826a23ffc34aa1b645ecf2a57e732f
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"  # Changed host port to 8081
    depends_on:
      - db

volumes:
  postgres_data: